#pragma once

struct P27_WindowMapLookup {

  /*p27.LENA*/ bool LENA;
  /*p27.MYMA*/ bool MYMA;
  /*p27.XUHA*/ bool XUHA;
  /*p27.VYNO*/ bool VYNO;
  /*p27.VUJO*/ bool VUJO;
  /*p27.VYMU*/ bool VYMU;
  /*p27.MOSU*/ bool MOSU;
  /*p27.LYRY*/ bool LYRY;
  /*p27.SYLO*/ bool SYLO;
  /*p27.ROXY*/ bool ROXY;
  /*p27.POVA*/ bool POVA;
  /*p27.NETA*/ bool NETA;
  /*p27.POTU*/ bool POTU;
  /*p27.PORE*/ bool PORE;
  /*p27.VYPO*/ bool VYPO;

  /*p27.MOFU*/ bool MOFU;
  /*p27.NYDY*/ bool NYDY;
  /*p27.NYXU*/ bool NYXU;

  /*p27.SECA*/ bool SECA;

  /*p27.NAZE*/ bool NAZE;
  /*p27.PEBO*/ bool PEBO;
  /*p27.POMO*/ bool POMO;
  /*p27.NEVU*/ bool NEVU;
  /*p27.NOJO*/ bool NOJO;
  /*p27.PAGA*/ bool PAGA;
  /*p27.PEZO*/ bool PEZO;
  /*p27.NUPA*/ bool NUPA;
  /*p27.PALO*/ bool PALO;
  /*p27.NELE*/ bool NELE;
  /*p27.PAFU*/ bool PAFU;
  /*p27.ROGE*/ bool ROGE;
  /*p27.SARY*/ bool SARY;
  /*p27.REPU*/ bool REPU;
  /*p27.REJO*/ bool REJO;
  /*p27.NEZO*/ bool NEZO;
  /*p27.NORY*/ bool NORY;
  /*p27.NONO*/ bool NONO;
  /*p27.PASE*/ bool PASE;
  /*p27.MYLO*/ bool MYLO;
  /*p27.PUWU*/ bool PUWU;
  /*p27.PUHO*/ bool PUHO;
  /*p27.NYTU*/ bool NYTU;
  /*p27.PUKY*/ bool PUKY;
  /*p27.NUFA*/ bool NUFA;
  /*p27.NOGY*/ bool NOGY;
  /*p27.NUKO*/ bool NUKO;
  /*p27.ROZE*/ bool ROZE;
  /*p27.PAHA*/ bool PAHA;
  /*p27.SUHA*/ bool SUHA;
  /*p27.SYBY*/ bool SYBY;
  /*p27.SOZU*/ bool SOZU;
  /*p27.PECU*/ bool PECU;
  /*p27.RONE*/ bool RONE;
  /*p27.POHU*/ bool POHU;




  /*p27.PANY*/ bool PANY;
  /*p27.SEKO*/ bool SEKO;
  /*p27.ROMO*/ bool ROMO;
  /*p27.SUVU*/ bool SUVU;
  /*p27.TAVE*/ bool TAVE;
  /*p27.XAHY*/ bool XAHY;
  /*p27.XOFO*/ bool XOFO;
  /*p27.XACO*/ bool XACO;
  /*p27.PYNU*/ bool PYNU;
  /*p27.NUNY*/ bool NUNY;
  /*p27.NOCU*/ bool NOCU;
  /*p27.PUKU*/ bool PUKU;
  /*p27.RYDY*/ bool RYDY;
  /*p27.TUXY*/ bool TUXY;
  /*p27.SUZU*/ bool SUZU;
  /*p27.TEVO*/ bool TEVO;
  /*p27.PASO*/ bool PASO;
  /*p27.VETU*/ bool VETU;
  /*p27.ROCO*/ bool ROCO;
  /*p27.NYFO*/ bool NYFO;
  /*p27.WAZY*/ bool WAZY;
  /*p27.SYNY*/ bool SYNY;
  /*p27.NOPA*/ bool NOPA;
  /*p27.PYCO*/ bool PYCO;
  /*p27.NUNU*/ bool NUNU;
  /*p27.RYKU*/ bool RYKU;
  /*p27.ROGA*/ bool ROGA;
  /*p27.RUBU*/ bool RUBU;
  /*p27.NYZE*/ bool NYZE;
  /*p27.PUXA*/ bool PUXA;
  /*p27.RYFA*/ bool RYFA;
  /*p27.RENE*/ bool RENE;
  /*p27.SOVY*/ bool SOVY;
  /*p27.MOCE*/ bool MOCE;
  /*p27.LEBO*/ bool LEBO;
  /*p27.LAXE*/ bool LAXE;
  /*p27.MYSO*/ bool MYSO;
  /*p27.NAKO*/ bool NAKO;
  /*p27.NOFU*/ bool NOFU;
  /*p27.NOGU*/ bool NOGU;
  /*p27.NENY*/ bool NENY;
  /*p27.LURY*/ bool LURY;
  /*p27.LONY*/ bool LONY;
  /*p27.LUSU*/ bool LUSU;
  /*p27.LYZU*/ bool LYZU;
  /*p27.LAXU*/ bool LAXU;
  /*p27.MESU*/ bool MESU;
  /*p27.NYVA*/ bool NYVA;
  /*p27.LOVY*/ bool LOVY;
  /*p27.WYKA*/ bool WYKA;
  /*p27.WODY*/ bool WODY;
  /*p27.WOBO*/ bool WOBO;
  /*p27.WYKO*/ bool WYKO;
  /*p27.XOLO*/ bool XOLO;
  /*p27.TUFU*/ bool TUFU;
  /*p27.TAXA*/ bool TAXA;
  /*p27.TOZO*/ bool TOZO;
  /*p27.TATE*/ bool TATE;
  /*p27.TEKE*/ bool TEKE;
  /*p27.XEJA*/ bool XEJA;
  /*p27.XAMO*/ bool XAMO;
  /*p27.XAHE*/ bool XAHE;
  /*p27.XULO*/ bool XULO;
  /*p27.WUJU*/ bool WUJU;
  /*p27.VYTO*/ bool VYTO;
  /*p27.VEHA*/ bool VEHA;
  /*p27.VACE*/ bool VACE;
  /*p27.VOVO*/ bool VOVO;
  /*p27.VULO*/ bool VULO;
  /*p27.VEVY*/ bool VEVY;
  /*p27.VEZA*/ bool VEZA;
  /*p27.VOGU*/ bool VOGU;
  /*p27.RYCE*/ bool RYCE;
  /*p27.VEKU*/ bool VEKU;
  /*p27.TAKA*/ bool TAKA;
  /*p27.TUKU*/ bool TUKU;
  /*p27.SOWO*/ bool SOWO;
  /*p27.TEKY*/ bool TEKY;
  /*p27.SOBU*/ bool SOBU;
  /*p27.SUDA*/ bool SUDA;
};



