#pragma once

struct P30_SpriteStore {

  void tick(const Gameboy& a, const Gameboy& b, Gameboy& c);

  /*p30.WEZA*/ bool IDX_0;
  /*p30.WUCO*/ bool IDX_1;
  /*p30.WYDA*/ bool IDX_2;
  /*p30.ZYSU*/ bool IDX_3;
  /*p30.WYSE*/ bool IDX_4;
  /*p30.WUZY*/ bool IDX_5;
  
  /*p30.WENU*/ bool LINE_0;
  /*p30.CUCU*/ bool LINE_1;
  /*p30.CUCA*/ bool LINE_2;
  /*p30.CEGA*/ bool LINE_3;

  bool CYKE,WUDA;
  bool XECU,YDUF,XOBE,ZUZE,XEDY,XADU;

  bool WOCY,ELYC,WABO,EZOC,WYWY,WATO,ZUDO,YBUK,ZYTO,YKOZ;
  bool WAJA,WOXY,XYRE,WERU,WEPY,WUXU,BYDO,BUCE,BOVE,BEVY;
  bool EVYT,WABA,ETAD,ELEP,WYGO,WAKO,WANA,WAXE,WABU,YPOZ;
  bool BEMO,CYBY,BETY,CEGY,CELU,CUBO,BEFE,BYRO,BACO,AHUM;
  bool DALO,DALY,DUZA,WAGA,DYNY,DOBO,AWAT,BACE,BODU,BUJA;
  bool DEZU,EFUD,DONY,DOWA,DYGO,ENAP,ZYPO,ZEXE,YJEM,YWAV;
  bool AXEC,CYRO,CUVU,APON,AFOZ,CUBE,ZABY,ZUKE,WUXE,WERE;
  bool YHAL,YRAD,XYRA,YNEV,ZOJY,ZARO,CAWO,BYME,COHO,GATE;
  bool ZETU,ZECE,ZAVE,WOKO,ZUMU,ZEDY,GOFO,WEHE,AJAL,BUKY;

  bool AXUV,BADA,APEV,BADO,BEXY,BYHE,AFYM,AZAP,AFUT,AFYX;
  bool GECU,FOXY,GOHU,FOGO,GACY,GABO,ZUBE,ZUMY,ZEXO,ZAFU;
  bool XYNU,XEGE,XABO,WANU,XEFE,XAVE,CUMU,CAPO,CONO,CAJU;
  bool FUZO,GESY,FYSU,FEFA,GYNO,GULE,XYGO,XYNA,XAKU,YGUM;
  bool CAJY,CUZA,COMA,CUFA,CEBO,CADU,ABUG,AMES,ABOP,AROF;
  bool EKAP,ETAV,EBEX,GORU,ETYM,EKOP,ANED,ACEP,ABUX,ABEG;
  bool DAFU,DEBA,DUHA,DUNY,DESE,DEVY,ZURY,ZURO,ZENE,ZYLU;
  bool BOXA,BUNA,BULU,BECA,BYHU,BUHE,YKUK,YLOV,XAZY,XOSY;
  bool XUFO,XUTE,XOTU,XYFE,YZOR,YBER,DEWU,CANA,DYSY,FOFO;
  bool YGUS,YSOK,YZEP,WYTE,ZONY,YWAK,FYHY,GYHO,BOZU,CUFO;
};

